yagpt-key: "t1.9euelZqPzMucm5OKkcmayYnPls2Lx-3rnpWayMuYyZTLlY6JyciQiceOlMnl8_dqSlxG-e90XQ0s_d3z9yp5WUb573RdDSz9zef1656Vms7IkI_Oz4uQy5CMj8nPjYrG7_zF656Vms7IkI_Oz4uQy5CMj8nPjYrG.Gck0DxvlJFY3wYLrt6S9Q0sKJHDrvyGi2Hmo0lS9kTjv_MieZJa3_f-x1DLgpNeadEcT6B9T7300O2mg7aimCQ"
yagpt-model: "gpt://b1g788lsg3ebu9vohhji/yandexgpt-lite"
yagpt-temperature: 0.6
yagpt-max-tokens: 2000
yagpt-system-message: "Представь, что ты мудрая гадалка"

