yagpt-key: "t1.9euelZrMmpuOkIvGlJCZmsjMj8vPyu3rnpWamIySiYqWz8zIi8ubx5TMis_l8_cdc1dF-e9WLytz_t3z910hVUX571YvK3P-zef1656VmpeclJyViYqUmZWJl8jHysbI7_zF656VmpeclJyViYqUmZWJl8jHysbI.6QsHuhJ-xdjAFOrnwYPsQE3VcIwfQdVXZjng2q3v_RIKVl4jh5Xe5dUEf3eKnsNBBTkrkCjvBgKiWhxFamhaDQ"
yagpt-model: "gpt://b1g220bgvm635prvi53g/yandexgpt-lite"
yagpt-temperature: 0.6
yagpt-max-tokens: 2000
yagpt-system-message: "Представь, что ты мудрая гадалка"

db-dsn: "postgres://test:test@localhost:5432/test?sslmode=disable"

tg-token: "8096088977:AAEQJYPk2ihyfZ2badyeCfop_6oW8G78tRU"

