yagpt-key: "AQVNz5oU748RvmUL1kdM-N5sy2cRj3wIKenTY7VS"
yagpt-model: "gpt://b1g220bgvm635prvi53g/yandexgpt-lite"
yagpt-temperature: 0.6
yagpt-max-tokens: 2000
yagpt-system-message: "Представь, что ты мудрая гадалка"

db-dsn: "postgres://test:test@localhost:5432/test?sslmode=disable"

tg-token: "7742188242:AAE2_HnGqKiihUwjTrA8gkc0_a9tG-4wZ5k"

