networks:
  net:
    driver: bridge

services:
  service:
    image: glaphyra
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '8080:8080'
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./internal/pkg/db/migrations:/app/migrations/
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U test -d test
      interval: 10s
      timeout: 3s
      retries: 5